# on: [push]

# jobs:
# hello_world_job:
# runs-on: ubuntu-latest
# name: A job to say hello

# steps:

# - uses: actions/checkout@v3

# - run: |

# echo "Hello World"

name: hello-world
on: push
jobs:
  build:
       runs-on: ubuntu-latest
         steps:
              -uses:actions/checkout@v3
              -run:| 
               echo "Hello World!
